# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f88010f4d70cb40f3ea3dd40c182e0079c48adff4aa9f1ed7095307c7a66beb0eb37acd743b58a1f3a0f89cf2752a636f9c078121706c265c7adf870d92199c8

test:
  secret_key_base: d4fb2b53558e7fde7ac5f9f59062fc32bd83703ebd2ec104e8260d05eb1ece6bbadff09dab2e859705c8062b83c7daca818a096d44ea9ecf94cc6c2b75eebeee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
